### ISSUE TITLE
Pass a callback to WS.send(...)

### ISSUE THREAD

**Issue by laino** [nojvek/noice-json-rpc#2]
WS.send(...) will throw errors when there's no callback:

https://github.com/websockets/ws/blob/master/lib/WebSocket.js#L355

Resulting in stuff like:
```
Error: not opened
    at WebSocket.send (/home/lain/git/final-pm/node_modules/ws/lib/WebSocket.js:355:18)
    at Server._send (/home/lain/git/final-pm/node_modules/noice-json-rpc/lib/noice-json-rpc.js:235:16)
    at Server._sendError (/home/lain/git/final-pm/node_modules/noice-json-rpc/lib/noice-json-rpc.js:238:14)
    at result.then.catch (/home/lain/git/final-pm/node_modules/noice-json-rpc/lib/noice-json-rpc.js:193:38)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

**Comment by laino** [comment]
@nojvek ping because you're not `Watch`ing your own repo ;)

**Comment by nojvek** [comment]
Will take a look.

**Comment by seantanly** [comment]
@laino @nojvek 

Reading https://github.com/websockets/ws#error-handling-best-practices
only by using the callback and checking that the `error` argument is `undefined`, then we can be sure the send has been completed. And that both immediate and async write failures are captured within the `error` argument.

Using only try/catch as the PR #3, as noted in the above, 
> // Immediate errors can also be handled with `try...catch`, but **note** that
// since sends are inherently asynchronous, socket write failures will *not* be
// captured when this technique is used.

Since the lib is returning a Promise, we should try to at least capture the async write failures and return them as part of the Promise rejection, if not there is no other way the end user can handle them?

**Comment by laino** [comment]
I agree that this would be cleaner, but if that ws lib got anything right it should at least emit errors on the socket. Also since any error means the connection is now dead, we will learn about it at the next write (or with the close event) anyways.

I cba to do anything but this quick fix though.

**Comment by nojvek** [comment]
My apologies folks. I'm on vacation at the moment but will look at the
problem closely as soon as I get a block of time with good interest.


Is there a block of code that could give me better repro of the websocket
problem. Just wanna ensure were all on the same page.

Thanks.

**Comment by seantanly** [comment]
@laino Thanks for the fix, it's definitely an improvement! 👍  
I see your points, and looking at the src, it will take a lot more changes for the library to handle the async socket errors out of the box.

@nojvek I came here from your https://github.com/nojvek/chrome-remote-debug-protocol which offered a typescript (definition) ready interface lib. Thank you for creating it! 

I don't have the code that can reproduce async write errors. I'm not familiar with node websocket libs, and it appears to me that `ws` seems like the most popular choice. Digging into it, the callback boils down to 

Ref 1: https://github.com/websockets/ws/blob/56f80625399de02abfe6c0d718ea5a8939969318/lib/Sender.js#L372
Ref 2: https://nodejs.org/api/net.html#net_socket_write_data_encoding_callback
Ref 3: https://github.com/nodejs/node/issues/11973

and adding the callback would mean changing the `LikeSocket` interface to 
`send(message: string, cb: (error?: any) => void): void`

My initial thoughts with that is, the Promise returned from `call` would include async write errors in its rejection. And that we can add a Promise return to `notify` which would indicate (un)successful sending of data on the socket. However, Ref 3 suggests the callback isn't reliably always called, thus can't be relied upon for resolving/rejecting `notify` Promise.

In any case, I recall this library aims to be compatible with any `LikeSocket` interface, so it is probably unreasonable for the library to do comprehensive error handling that's implementation specific, that isn't part of JSON RPC spec. 

So perhaps it is enough to update the README to remind users to do their own error handling, and the example that's using `ws` to include some error handling indication.

```typescript
const websocket = new WebSocket("ws://localhost:8080")
websocket.on('error', error => {
    console.log('socket error', error)
    // need to recreate rpc.Client with new websocket
})
const api = new rpc.Client(websocket, {logConsole: true}).api()
```

**Comment by nojvek** [comment]
Thanks for the clarification Sean.

Feel free to send a documentation PR.

I'll look into writing some more tests for error handling situations and
rejecting promises.
