### ISSUE TITLE
Working with devtools-protocol

### ISSUE THREAD

**Issue by roblourens** [nojvek/noice-json-rpc#8]
Congrats on getting the protocol generator into devtools-protocol! I am switching to that and want to keep using noice-json-rpc, but it doesn't work with the `Debugger.on('scriptParsed, ...` style event handlers, it only expects `Debugger.onScriptParsed(...`.

Are you planning on making the first type work? I could provide a PR? Or is there a way to make them work together that I don't see?

**Comment by nojvek** [comment]
Thanks Rob, Its not fully done yet. I need to implement the schema validator so devtools-protocol is always guaranteed to be valid.  `Debugger.on(...` syntax was a last minute suggestion from the puppetteer team. I do like it.

Getting  devtools-protocol format to work with noice-json-rpc would be great.  Let me make a quick fix and ask you for a review.

**Comment by nojvek** [comment]
@roblourens FYI, I added you as collaborator

**Comment by roblourens** [comment]
Thanks!
